(function(r,z,U){r.execute(function(){r.when("A","jQuery","atf").execute(function(M,d){M.on.ready(function(){function g(a,b,c,e,f){d(a).slideToggle(300);d(b).slideToggle(300);d(c).toggleClass("tmmShowPrompt tmmHidePrompt");d(e).toggleClass("tmmShowPrompt tmmHidePrompt");d(f).toggleClass("rotate")}function m(a){a.position();a.width();d(".swatchElement");a.find(".swatchElement").each(function(){d(this).attr("data-width",d(this).width())});d("#formats").find(".a-row").removeClass("nonJSFormats")}function b(){var a=
d("#formats"),b=a.width()-40,c=0;a.find(".swatchElement").each(function(){d(this).is(":visible")&&(c+=d(this).width())});c>b?d(a.find(".swatchElement:visible").get().reverse()).each(function(){var a=0,e=!1;d(this).find(".format").hasClass("a-button-selected")?(a=d(this).prev(".swatchElement").width(),e=d(this).prev(".swatchElement").is(":hidden"),d(this).prev(".swatchElement").hide()):(a=d(this).width(),e=d(this).is(":hidden"),d(this).hide());e||(c-=a);return c>b}):c<b&&a.find(".swatchElement").each(function(){if(d(this).is(":hidden"))return d(this).attr("data-width")<=
b-c&&d(this).show(),!1})}var a=0,c=0,e,f=function(a){"undefined"!=typeof a&&(e=new a.ImpressionLogger("dpbxapps","bxapps-atfMarker",!0,!0))};"undefined"!=typeof amznJQ?amznJQ.available("DPClientLogger",function(){f(z.DPClientLogger)}):r.when("DPClientLogger").execute(f);M.declarative("tmm-see-more-editions-click",["click"],function(a){var b=a.data,c=b.metabindingUrl;if(a.$target.hasClass("a-link-expander")||a.$target.parent().hasClass("a-link-expander")){var b=b.metabindingPlaceHolder,e="#metabinding_row_top_"+
b,f="#metabinding_row_bottom_"+b,h="#editionsSeePrompt_"+b,l="#editionsHidePrompt_"+b,m="#editionsIcon_"+b,r="isAjaxComplete_"+b,x="isAjaxInProgress_"+b;a="#tmmSpinnerDiv_"+b;var A=M.state("mediamatrix-state"),b=A["url_"+b].replace(/&amp;/g,"&");d("#formats .tmmErrorClass").hide();"1"===A[r]||"1"===A[x]?g(e,f,h,l,m):(M.ajax(b,{method:"get",success:function(){A[r]="1";M.state("mediamatrix-state",A);g(e,f,h,l,m)},indicator:d(a),error:function(){d($tmmErrorDiv).show();A[x]="0";M.state("mediamatrix-state",
A)}}),A[x]="1",M.state("mediamatrix-state",A))}else"#"!==c&&(z.location=c)});if(0<d("#formats > .a-link-expander").length){var h=z.ue;h&&h.count&&h.count("mediaMatrixExpanderPresent",1)}d("#formats > .a-link-expander").click(function(){g("#tmmSwatches","#twister","#showMoreFormatsPrompt","#hideMoreFormatsPrompt","#formatsIcon");if(!c){var b=z.ue;b&&b.count&&b.count("mediaMatrixExpanderClicked",1);c=1}e&&d("#twister").is(":visible")&&!a&&(e.logImpression("tmm-show-more-formats-viewed"),a=1)});var h=
M.state("mediamatrix-state"),l="1";"undefined"!==typeof h&&"undefined"!==typeof h.showHybridMediaMatrix&&"1"===h.showHybridMediaMatrix?l="0":"undefined"!==typeof h&&"undefined"!==typeof h.isDvdWeblabEnabled&&"1"===h.isDvdWeblabEnabled&&(l="0");"1"===l&&(d("#formats.responsive").each(function(){m(d(this))}),b(),M.on("resize",b));d("#formats .unselected .format").mouseenter(function(){d(this).find(".a-color-secondary").addClass("a-color-price").removeClass("a-color-secondary")}).mouseleave(function(){d(this).find(".a-color-price").addClass("a-color-secondary").removeClass("a-color-price")});
d("#landingItemRentalLink").attr("href","javascript:document.getElementById('rentBuySection').click();")})});r.when("A","jQuery","a-dropdown").execute(function(r,d,g){function m(a){return a?a.replace(/&#0/g,"&#"):undef}function b(a){for(var b=a.getOptions(),b=b?b.size():0,c=1;c<b;c++)a.removeOption(1)}function a(a,b){var c=a.getOption(0),e=c.info()[0];c.remove();d.each(b,function(b,c){a.addOption({text:p[m(c)],value:c,css_class:"dropdownAvailable"},1)});a.addOption(e,0);a.val(e.value)}function c(c){D=
c.value;b(u);"-1"!==D&&(e(),a(u,Object.keys(l[m(D)])))}function e(){Object.keys||(Object.keys=function(){var a=Object.prototype.hasOwnProperty,b=!{toString:null}.propertyIsEnumerable("toString"),c="toString toLocaleString valueOf hasOwnProperty isPrototypeOf propertyIsEnumerable constructor".split(" "),d=c.length;return function(e){if("object"!==typeof e&&("function"!==typeof e||null===e))throw new TypeError("Object.keys called on non-object");var f=[],g;for(g in e)a.call(e,g)&&f.push(g);if(b)for(g=
0;g<d;g++)a.call(e,c[g])&&f.push(c[g]);return f}}())}function f(a){w=a.value;"-1"!==w&&"-1"!==D&&(z.location=n[l[m(D)][m(w)]])}function h(a){a=a.value;"-1"!==a&&(z.location=n[m(a)])}var l,k=r.state("dcdMetaData");if(k){var n=k.asinToDetailPageURLMap,p=k.truncatedValuesMap,q=k.dimensionKeys,t=q[0],D=-1,w=-1,u;2===q.length?(l=k.doubleValuesToAsinMap,k=q[1],q=g.getSelect("native_dcd_dropdown_"+t),u=g.getSelect("native_dcd_dropdown_"+k),q.setValue("-1"),u.setValue("-1"),b(u),r.on("a:dropdown:selected:"+
t,c),r.on("a:dropdown:selected:"+k,f)):(q=g.getSelect("native_dcd_dropdown_"+t),(g=k.selectedAsin)?q.setValue(g):q.setValue("-1"),r.on("a:dropdown:selected:asin-redirect",h))}})})})(function(){var r=window.AmazonUIPageJS||window.P,z=r._namespace||r.attributeErrors;return z?z("TwisterHardlinesDetailPageAsset"):r}(),window);
/* ******** */
(function(r,z,U){r.execute(function(){r.when("A","jQuery","atf").execute(function(r,d,g){function m(){var b=parseInt(d("#byline").width()),a=0;d("#byline .author").each(function(){d(this).is(".notFaded")&&(a+=d(this).outerWidth())});a+=d("#byline .more").outerWidth();if(a>b){var c=d("#byline .author.notFaded").length;d(d("#byline .author.notFaded").get().reverse()).each(function(e){a>b&&e<c-1&&(e=d(this).width(),d(this).removeClass("notFaded"),d(this).fadeOut(10,function(){d(this).hide()}),a-=e,d("#byline .moreCount").html(d("#byline .author").length-
d("#byline .author.notFaded").length),d("#byline .more").addClass("notFaded").fadeIn(10))})}else if(a<b&&d("#byline .author.notFaded").length<d("#byline .author").length){var e=b-a;d("#byline .author").each(function(){if(!d(this).hasClass("notFaded")){var a=d(this).outerWidth();a<=e?(e-=a,d(this).addClass("notFaded").fadeIn(10),a=d("#byline .author").length-d("#byline .author.notFaded").length,0===a?d("#byline .more").removeClass("notFaded").fadeOut(10):(d("#byline .moreCount").html(a),d("#byline .more").addClass("notFaded").fadeIn(10))):
e=0}})}}d("#byline .showMoreLink").click(function(){d("#byline .author").each(function(){d(this).hasClass("notFaded")||d(this).addClass("notFaded").fadeIn(0);d("#byline .more").removeClass("notFaded").fadeOut(0)});return!1});d("#byline .contributorNameID").mouseenter(function(){var b=d(this).attr("data-asin"),a={},c="isAjaxComplete_"+b,e="isAjaxInProgress_"+b,f=r.state("popoverImage-state");a.entityID=b;"1"!==f[c]&&"1"!==f[e]&&(d.ajax({url:"/gp/product/utility/by-line/book-contributor-details/ajax/author-image.html",
data:a,dataType:"html",timeout:1E3,success:function(a){d("#contributorImageContainer"+b).get(0).innerHTML=a;f[c]="1";r.state("popoverImage-state",f)},error:function(){f[e]="0";r.state("popoverImage-state",f)}}),f[e]="1",r.state("popoverImage-state",f))});(function(b){var a=parseInt(b.width()),c=parseInt(b.find(".more").outerWidth()),e=0;d("#byline .author").each(function(){d(this).is(".notFaded")&&(e+=d(this).outerWidth())});d("#byline .more").attr("data-width",c);var f=a-c;if(f>e)b.find(".author").each(function(){var a=
d(this).index();3<=parseInt(a)?(a=d(this).outerWidth(),d(this).attr("data-width",a),a<f?(f-=a,d(this).addClass("notFaded"),d(this).fadeIn("slow")):(f=0,d(this).fadeOut("slow"))):(a=d(this).outerWidth(),d(this).attr("data-width",a),f-=a)});else{var g=d("#byline .author.notFaded").length;d(d("#byline .author.notFaded").get().reverse()).each(function(a){f<e&&a<g-1&&(a=d(this).outerWidth(),e-=a,d(this).fadeOut("slow").removeClass("notFaded"))})}a=b.find(".author").length-b.find(".author.notFaded").length;
0<a&&(b.find(".moreCount").html(a),b.find(".more").fadeIn("slow"),b.find(".more").addClass("notFaded"))})(r.$("#byline"));d(z).resize(function(){m()})});r.when("A","jQuery").register("product-description-fix",function(r,d){return{fixTableIssue:function(){d("#productDescription .productDescriptionWrapper table").each(function(){var g=d(this).attr("width");"undefined"!==typeof g?d(this).css("width",g):d(this).css("width","auto")})}}})})})(function(){var r=window.AmazonUIPageJS||window.P,z=r._namespace||
r.attributeErrors;return z?z("PInfoHardlinesDetailPageAsset"):r}(),window);
/* ******** */
(function(r,z,U){r.execute(function(){r.when("A","jQuery","atf").register("accordionBuyBoxJS",function(M,d,g){var m={updateCssClass:function(b){var a=d("#rbbContainer");a.find(".selected .a-icon-radio-active").removeClass("a-icon-radio-active").addClass("a-icon-radio-inactive");a.find(".selected .offer-price").removeClass("a-color-price").addClass("a-color-secondary");b.parents(".rbbSection").removeClass("unselected").addClass("selected");b.parents(".rbbSection").toggleClass("dp-accordion-active",
500);b.find(".a-icon-radio-inactive").removeClass("a-icon-radio-inactive").addClass("a-icon-radio-active");b.find(".offer-price").removeClass("a-color-secondary").addClass("a-color-price");d("#rbbContainer .rbbSection .rbbContent").find(".offer-price").removeClass("a-color-secondary").addClass("a-color-price")},animate:function(b){var a=d("#rbbContainer"),c=b.attr("id"),e,f;a.find(".rbbSection").each(function(a,b){d(b).find(".rbbHeader")[0].id==c?e=d(b):d(b).hasClass("selected")&&(f=d(b))});f.find(".rbbContent").slideUp(500,
function(){f.removeClass("selected").addClass("unselected");f.toggleClass("dp-accordion-active",500)});e.find(".rbbContent").slideDown(500);d.browser.msie&&7==parseInt(d.browser.version,10)&&(e.find(".rbbContent").css("display","inline"),setTimeout(function(){e.find(".rbbContent").css("display","block")},505))},oneClickJS:function(){d("#one-click-button, #one-click-button-ubb").click(function(){var b="https://"+z.location.host+d("#addToCart").attr("action");d("#addToCart").attr("action",b);return!0})},
usedBuyBoxJS:function(){d("#one-click-button-ubb, #usedbuyBox #add-to-cart-button-ubb").click(function(){var b=d("#addToCart"),a=b.attr("action").replace("ref=dp_start-bbf_1_glance","ref=dp_start-ubbf_1_glance");b.attr("action",a);return!0});r.when("a-popover").execute(function(b){var a=d("#usedItemConditionInfoLink"),c=b.create(a,{width:250,position:"triggerBottom",activate:M.capabilities.touch?"onmousemove":"onclick",closeButton:!1,popoverLabel:"Used condition details",name:"usedItemConditionDetailsPopover",
dataStrategy:"preload"});a.mouseleave(function(){c.hide()})})},initialize:function(){d(".rbbHeaderLink").attr("href","javascript:void(0);");d("#rbbContainer .rbbSection.unselected .dp-accordion-inner").hide();d("#rbbContainer .rbbSection .rbbHeader").click(function(b){d(b.target);b=d(this);b=b.hasClass("rbbHeader")?b:b.parents(".rbbHeader");if(b.parents(".rbbSection").hasClass("selected"))return!1;m.updateCssClass(b);d("#abbWrapper [id^=mbb-offeringID-]").each(function(){this.checked=!1});b=d(this);
m.animate(b);return!0});m.oneClickJS();m.usedBuyBoxJS()}};return m})})})(function(){var r=window.AmazonUIPageJS||window.P,z=r._namespace||r.attributeErrors;return z?z("OffersHardlinesDetailPageAsset"):r}(),window);
/* ******** */
