(function(a,d,w){function p(b){for(var a={},c,k,q=0;q<b.length;q++)k=b[q],c=k.r+k.s+k.m,k.c&&(a[c]||(a[c]=[]),a[c].push(b[q]));return a}function n(b){for(var a=1;a<arguments.length;a++){var c=arguments[a];try{if(c.isSupported)return c.send(b)}catch(k){}}}function h(){for(var b=0;b<A.length;b++)A[b]();E.length&&n(p(E.splice(0,E.length)),O,L,I);z=M=0}function l(c,J,r){r=r||{};0===r.bf&&b.isBF||(c={r:r.r||b.rid,s:r.s||a.ue_sid,m:r.m||a.ue_mid,mkt:r.mkt||a.ue_mkt,sn:r.sn||a.ue_sn,c:J,d:c,t:r.t||b.d(),
cs:r.c&&a.ue_qsl},r.b?n(p([c]),O,I):r.nb?n(p([c]),O,L,I):r.img||F[J]?n(p([c]),I):r.n?(E.push(c),0===N?h():z||(z=d.setTimeout(h,N))):(E.push(c),M||(M=d.setTimeout(h,H))))}function t(b,a,c){K++;K==x?l({m:"Max number of Forester Logs exceeded",f:"forester-client.js",logLevel:"ERROR"},d.ue_err_chan||"jserr"):K<x&&l(b,a,c)}function m(){if(!C){for(var b=0;b<f.length;b++)f[b]();for(b=0;b<A.length;b++)A[b]();n(p(E.splice(0,E.length)),O,I);C=!0}}var g={};(function(){function b(a){return 10>a?"0"+a:a}function a(b){k.lastIndex=
0;return k.test(b)?'"'+b.replace(k,function(b){var a=B[b];return"string"===typeof a?a:"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+b+'"'}function c(b,v){var k,B,g,e,u=q,G,D=v[b];D&&"object"===typeof D&&"function"===typeof D.toJSON&&(D=D.toJSON(b));"function"===typeof d&&(D=d.call(v,b,D));switch(typeof D){case "string":return a(D);case "number":return isFinite(D)?String(D):"null";case "boolean":case "null":return String(D);case "object":if(!D)return"null";q+=f;G=[];if("[object Array]"===
Object.prototype.toString.apply(D)){e=D.length;for(k=0;k<e;k+=1)G[k]=c(k,D)||"null";g=0===G.length?"[]":q?"[\n"+q+G.join(",\n"+q)+"\n"+u+"]":"["+G.join(",")+"]";q=u;return g}if(d&&"object"===typeof d)for(e=d.length,k=0;k<e;k+=1)"string"===typeof d[k]&&(B=d[k],(g=c(B,D))&&G.push(a(B)+(q?": ":":")+g));else for(B in D)Object.prototype.hasOwnProperty.call(D,B)&&(g=c(B,D))&&G.push(a(B)+(q?": ":":")+g);g=0===G.length?"{}":q?"{\n"+q+G.join(",\n"+q)+"\n"+u+"}":"{"+G.join(",")+"}";q=u;return g}}"function"!==
typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(a){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+b(this.getUTCMonth()+1)+"-"+b(this.getUTCDate())+"T"+b(this.getUTCHours())+":"+b(this.getUTCMinutes())+":"+b(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(b){return this.valueOf()});var k=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
q,f,B={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},d;"function"!==typeof g.stringify&&(g.stringify=function(b,a,v){var k;f=q="";if("number"===typeof v)for(k=0;k<v;k+=1)f+=" ";else"string"===typeof v&&(f=v);if((d=a)&&"function"!==typeof a&&("object"!==typeof a||"number"!==typeof a.length))throw Error("JSON.stringify");return c("",{"":b})})})();var e=function(){function b(a,c){if(null==a)return c.push("!n");if("number"===typeof a)return c.push("!"+a);if("string"===
typeof a)return"\\"==a[a.length-1]?c.push("'"+a.replace(/'/g,"\\'")+"u005C'"):c.push("'"+a.replace(/'/g,"\\'")+"'");if("boolean"===typeof a)return c.push(a?"!t":"!f");if(a instanceof Array){c.push("*");for(var k=0;k<a.length;k++)b(a[k],c);return c.push(")")}if("object"==typeof a){c.push("(");for(k in a)a.hasOwnProperty(k)&&(c.push(k),b(a[k],c));return c.push(")")}return c.push("!n")}return{stringify:function(a){var c=[];b(a,c);return c.join("")}}}(),u=a.ue_qsl||2E3,x=1E3,y=function(){},c=d.JSON&&
d.JSON.stringify||g&&g.stringify,q=e.stringify,b=a.ue||{},e=a.uet||y;(a.uet||y)("bb","ue_frst_v2",{wb:1});var G="//"+a.ue_furl+"/1/batch/1/OE/",E=[],f=[],A=[],C=!1,z,M,N=void 0===a.ue_hpfi?1E3:a.ue_hpfi,H=void 0===a.ue_lpfi?1E4:a.ue_lpfi,F={"scheduled-delivery":1},K=0,L=function(){function v(){if(d.XDomainRequest){var b=new XDomainRequest;b.onerror=y;b.ontimeout=y;b.onprogress=y;b.onload=y;b.timeout=0;return b}if(d.XMLHttpRequest){b=new XMLHttpRequest;if(!("withCredentials"in b))throw"";return b}if(d.ActiveXObject){for(var a=
0;a<r.length&&!b;a++)try{b=new ActiveXObject(r[a]),r=[r[a]]}catch(c){}return b}}function J(c){for(var v=[],r=c[0]||{},B=0;B<c.length;B++){var J={};J[c[B].c]=c[B].d;v.push(J)}return{rid:r.r||b.rid,sid:r.s||a.ue_sid,mid:r.m||a.ue_mid,mkt:r.mkt||a.ue_mkt,sn:r.sn||a.ue_sn,reqs:v}}var r="MSXML2.XMLHTTP.6.0 MSXML2.XMLHTTP.5.0 MSXML2.XMLHTTP.4.0 MSXML2.XMLHTTP.3.0 MSXML2.XMLHTTP Microsoft.XMLHTTP".split(" ");return{send:function(b){for(var a in b)if(b.hasOwnProperty(a)&&b[a].length){var r=J(b[a]),B=v();
if(!B)throw"";B.open("POST",G,!0);B.setRequestHeader&&B.setRequestHeader("Content-type","text/plain");B.send(c(r))}},buildPOSTBodyLog:J,isSupported:!0}}(),I=function(){return{send:function(v){for(var J in v)if(v.hasOwnProperty(J)){for(var r=v[J],k=r,f={},g=void 0,B=0;B<k.length;B++)g=k[B].c,f[g]||(f[g]=[]),f[g].push(k[B]);var r=r[0]||{},k=r.sn||a.ue_sn,r=G+(r.m||a.ue_mid)+":"+(r.s||a.ue_sid)+":"+(r.r||b.rid)+(k?":"+k:""),k=[],g=r,B=[],d=void 0;for(d in f)if(f.hasOwnProperty(d))for(var Q=0;Q<f[d].length;Q++){var e=
f[d][Q],S=encodeURIComponent((e.cs?q:c)(e.d));B.push({l:S,t:e.t,p:1,c:d,d:e.cs?"c":"j"})}f=B;B=void 0;d="$";for(e=0;e<f.length;){Q=f[e];B!=Q.c?(g+=d+Q.c+"=",d="&",B=Q.c):g+=",";var S=g,m=Q.d+":",h=Q,g=(h.l.match(".{1,"+(u-g.length)+"}[^%]{0,2}")||[])[0]||"";h.l=h.l.substr(g.length);g=S+(m+g+":"+Q.t);if(Q.l)g+=":"+Q.p++ +"_",k.push(g),g=r,d="$",B=0;else if(e++,1!=Q.p)for(g+=":"+Q.p+"_"+Q.p,S=0;S<Q.p-1;S++)k[k.length-S-1]+=Q.p}k.push(g);r=k;for(k=0;k<r.length;k++)(new Image).src=r[k]}},isSupported:!0}}(),
O=function(){return{send:function(b){for(var a in b)if(b.hasOwnProperty(a)){var r=L.buildPOSTBodyLog(b[a]);if(!navigator.sendBeacon(G,c(r)))throw"";}},isSupported:!!navigator.sendBeacon}}();b._fic=I;b._fac=L;b._fbc=O;b._flq=E;b.sid=b.sid||a.ue_sid;b.mid=b.mid||a.ue_mid;b.furl=b.furl||a.ue_furl;b.sn=b.sn||a.ue_sn;b.isBF=function(){var a=d.performance||d.webkitPerformance,c=w.ue_backdetect&&w.ue_backdetect.ue_back&&document.ue_backdetect.ue_back.value,r=b.bfini;return a&&a.navigation&&2===a.navigation.type||
1<r||!r&&1<c}();try{d.amznJQ&&d.amznJQ.declareAvailable&&d.amznJQ.declareAvailable("forester-client"),d.P&&d.P.register&&d.P.register("forester-client",y)}catch(P){a.ueLogError(P,{logLevel:"WARN"})}(function(){b.log&&b.log.isStub&&(b.log.replay(function(b,a,c){var k=b[2]||{};k.t=a;k.r=c;k.n=1;t(b[0],b[1],k)}),b.onunload.replay(function(b){f.push(b[0])}),b.onflush.replay(function(b){A.push(b[0])}))})();b.log=t;b.log.reset=function(){K=0};b.onunload=function(b){f.push(b)};b.onflush=function(b){A.push(b)};
b.attach("beforeunload",m);b.attach("pagehide",m);e("ld","ue_frst_v2",{wb:1})})(ue_csm,window,document);
(function(a,d){function w(a){if(a)return a.replace(/^\s+|\s+$/g,"")}function p(c,q){if(!c)return{};c.m&&c.m.message&&(c=c.m);var b=q.m||q.message||"",b=c.m&&c.m.message?b+c.m.message:c.m&&c.m.target&&c.m.target.tagName?b+("Error handler invoked by "+c.m.target.tagName+" tag"):c.m?b+c.m:c.message?b+c.message:b+"Unknown error",b={m:b,f:c.f||c.sourceURL||c.fileName||c.filename||c.m&&c.m.target&&c.m.target.src,l:c.l||c.line||c.lineno||c.lineNumber,c:c.c?""+c.c:c.c,s:[],t:a.ue.d(),name:c.name,type:c.type,
csm:g+" "+(c.fromOnError?"onerror":"ueLogError")},d,h,f=0,l=0,p;d=c.stack||(c.err?c.err.stack:"");b.pageURL=q.pageURL||""+(window.location?window.location.href:"")||"missing";b.logLevel=q.logLevel||m;if(h=q.attribution)b.attribution=""+h;a.ue_hi_err&&(b.hi=a.ue.hi);if(d&&d.split)for(b.csm+=" stack",h=d.split("\n");f<h.length&&b.s.length<e;)(d=h[f++])&&b.s.push(w(d));else for(b.csm+=" callee",h=n(c.args||arguments,"callee"),l=f=0;h&&f<e;)p=u,h.skipTrace||(d=h.toString())&&d.substr&&(p=0===l?4*u:p,
p=1==l?2*u:p,b.s.push(d.substr(0,p)),l++),h=n(h,"caller"),f++;if(!b.f&&0<b.s.length&&(f=b)&&f.s){var t;d=0<f.s.length?f.s[0]:"";h=1<f.s.length?f.s[1]:"";d&&(t=d.match(y));t&&3==t.length||!h||(t=h.match(x));t&&3==t.length&&(f.f=t[1],f.l=t[2])}return b}function n(a,q){try{return a[q]}catch(b){}}function h(c,q){if(c){var b=p(c,q);a.ue.log(b,q.channel||t,{nb:1});try{if(!c.fromOnError){var g=d.console,e=d.JSON,f="Error logged with the Track&Report JS errors API(http://tiny/1covqr6l8/wamazindeClieUserJava): ";
if(g){if(e&&e.stringify)try{f+=e.stringify(b)}catch(u){f+="no info provided; converting to string failed"}else f+=b.m;"function"===typeof g.error?g.error(f,b):"function"===typeof g.log&&g.log(f,b)}}}catch(h){}}}function l(c,q){if(c&&!(a.ue_err.ec>a.ue_err.mxe)){a.ue_err.ec++;a.ue_err.ter.push(c);q=q||{};var b=c.logLevel||q.logLevel;q.logLevel=b;q.attribution=c.attribution||q.attribution;b&&b!=m||ue_err.ecf++;h(c,q)}}if(!a.ueLogError||a.ueLogError.isStub){var t=a.ue_err_chan||"jserr",m="FATAL",g="v5",
e=20,u=256,x=/\(?([^\s]*):(\d+):\d+\)?/,y=/.*@(.*):(\d*)/;h.skipTrace=1;p.skipTrace=1;l.skipTrace=1;(function(){if(a.ue_err.erl){var c=a.ue_err.erl.length,q,b;for(q=0;q<c;q++)b=a.ue_err.erl[q],h(b.ex,b.info);ue_err.erl=[]}})();a.ueLogError=l}})(ue_csm,window);
(function(a,d){a.ue_cel||(a.ue_cel=function(){function w(a,q){q?q.r=x:q={r:x,c:1};q.clog&&g.clog?g.clog(a,q.ns||t,q):q.glog&&g.glog?g.glog(a,q.ns||t,q):g.log(a,q.ns||t,q)}function p(){var a=h.length;if(0<a){for(var q=[],b=0;b<a;b++){var d=h[b].api;d.ready()?(d.on({ts:g.d,ns:t}),l.push(h[b]),w({k:"mso",n:h[b].name,t:g.d()})):q.push(h[b])}h=q}}function n(){if(!n.executed){for(var a=0;a<l.length;a++)l[a].api.off&&l[a].api.off({ts:g.d,ns:t});w({k:"eod",t0:g.t0,t:g.d()},{c:1});n.executed=1;for(a=0;a<l.length;a++)h.push(l[a]);
l=[];clearTimeout(m)}}var h=[],l=[],t=a.ue_cel_ns||"cel",m,g=a.ue,e=a.uet,u=a.uex,x=g.rid,y=d.requestAnimationFrame||function(a){a()};if(g.isBF)w({k:"bft",t:g.d()});else return"function"==typeof e&&e("bb","csmCELLSframework",{wb:1}),setTimeout(p,0),g.onunload(n),m=setTimeout(n,6E5),"function"==typeof u&&u("ld","csmCELLSframework",{wb:1}),{registerModule:function(a,q){h.push({name:a,api:q});w({k:"mrg",n:a,t:g.d()});p()},reset:function(a){w({k:"rst",t0:g.t0,t:g.d()});h=h.concat(l);l=[];for(var q=h.length,
b=0;b<q;b++)h[b].api.off(),h[b].api.reset();x=a||g.rid;p();clearTimeout(m);m=setTimeout(n,6E5);n.executed=0},timeout:function(a,q){return d.setTimeout(function(){y(a)},q)},log:w}}())})(ue_csm,window);
(function(a,d,w){a.ue_pdm||ue.isBF||(a.ue_pdm=function(){function p(){var b={w:l.width,aw:l.availWidth,h:l.height,ah:l.availHeight,cd:l.colorDepth,pd:l.pixelDepth},c={w:w.body.scrollWidth,h:w.body.scrollHeight};e&&e.w==b.w&&e.h==b.h&&e.aw==b.aw&&e.ah==b.ah&&e.pd==b.pd&&e.cd==b.cd||(e=b,e.t=m(),e.k="sci",y(e));u&&u.w==c.w&&u.h==c.h||(u=c,u.t=m(),u.k="doi",y(u));t=a.ue_cel.timeout(p,g)}function n(){y({k:"ebl",t:m()})}function h(){y({k:"efo",t:m()})}var l,t,m,g,e,u,x=a.ue,y=a.ue_cel.log,c=a.uet,q=a.uex;
"function"==typeof c&&c("bb","csmCELLSpdm",{wb:1});return{on:function(b){g=b.timespan||500;m=b.ts;l=d.screen;x.attach&&(x.attach("blur",n,d),x.attach("focus",h,d));b=d.location;y({k:"pmd",o:b.origin,p:b.pathname,t:m()});a.ue_cel.timeout(p,0);"function"==typeof q&&q("ld","csmCELLSpdm",{wb:1})},off:function(a){clearTimeout(t);x.detach&&(x.detach("blur",n,d),x.detach("focus",h,d));x.count&&(x.count("cel.PDM.TotalExecutions",0),x.count("cel.PDM.TotalExecutionTime",0),x.count("cel.PDM.AverageExecutionTime",
0/0))},ready:function(){return w.body&&a.ue_cel&&a.ue_cel.log},reset:function(){e=u=null}}}(),a.ue_cel&&a.ue_cel.registerModule("page module",a.ue_pdm))})(ue_csm,window,document);
(function(a,d){a.ue_vpm||ue.isBF||(a.ue_vpm=function(){function w(){var a=t(),c={w:d.innerWidth,h:d.innerHeight,x:d.pageXOffset,y:d.pageYOffset};n&&n.w==c.w&&n.h==c.h&&n.x==c.x&&n.y==c.y||(c.t=a,c.k="vpi",n=c,u(n,{clog:1}));h=0;m=t()-a;g+=1}function p(){h||(h=a.ue_cel.timeout(w,l))}var n,h,l,t,m=0,g=0,e=a.ue,u=a.ue_cel.log,x=a.uet,y=a.uex,c=e.attach,q=e.detach;"function"==typeof x&&x("bb","csmCELLSvpm",{wb:1});return{on:function(b){t=b.ts;l=b.timespan||100;a.ue_cel.timeout(w,0);c&&(c("scroll",p),
c("resize",p));"function"==typeof y&&y("ld","csmCELLSvpm",{wb:1})},off:function(a){clearTimeout(h);q&&(q("scroll",p),q("resize",p));e.count&&(e.count("cel.VPI.TotalExecutions",g),e.count("cel.VPI.TotalExecutionTime",m),e.count("cel.VPI.AverageExecutionTime",m/g))},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){n=void 0},getVpi:function(){return n}}}(),a.ue_cel&&a.ue_cel.registerModule("viewport module",a.ue_vpm))})(ue_csm,window);
(function(a,d,w){var p=a.ue||{};!p.isBF&&!a.ue_fem&&w.querySelector&&d.getComputedStyle&&[].forEach&&(a.ue_fem=a.ue_bwd?function(){function n(a,b){return a>b?3>a-b:3>b-a}function h(a,b,c){var v;a:{try{if(a){var k=a.getBoundingClientRect();v={x:k.left+c.x|0,y:k.top+c.y|0,w:k.width|0,h:k.height|0,d:(0===a.offsetWidth&&0===a.offsetHeight)|0}}else v=void 0;break a}catch(r){}v=void 0}if(v&&!a.cel_b)a.cel_b=v,E({n:a.cel_n,w:a.cel_b.w,h:a.cel_b.h,d:a.cel_b.d,x:a.cel_b.x,y:a.cel_b.y,t:b,k:"ewi",cl:a.className},
{clog:1});else{if(c=v)c=a.cel_b,k=v,c=k.d===c.d&&1===k.d?!1:!(n(c.x,k.x)&&n(c.y,k.y)&&n(c.w,k.w)&&n(c.h,k.h)&&c.d===k.d);c&&(a.cel_b=v,E({n:a.cel_n,w:a.cel_b.w,h:a.cel_b.h,d:a.cel_b.d,x:a.cel_b.x,y:a.cel_b.y,t:b,k:"ewi"},{clog:1}))}}function l(a,b,c){var v;v=a.c?w.getElementsByClassName(a.c):a.id?[w.getElementById(a.id)]:w.querySelectorAll(a.s);a.w=[];for(widgetIndex=0;widgetIndex<v.length;widgetIndex++){var k=v[widgetIndex];k&&(k.cel_n||(k.cel_n=k.getAttribute("cel_widget_id")||(a.id_gen||G)(k,widgetIndex)||
k.id),a.w.push(k),g(r,k,b,c))}}function t(a,b){f.contains(a)||E({n:a.cel_n,t:b,k:"ewd"},{clog:1})}function m(a){I.length&&ue_cel.timeout(function(){for(var b=U(),v=!1;U()-b<c&&!v;){for(v=P;0<v--&&0<I.length;){var r=I.shift();k[r.type](r.elem,r.time,r.pageOffset)}v=0===I.length}O++;m(a)},0)}function g(a,b,c,v){I.push({type:a,elem:b,time:c,pageOffset:v})}function e(a,c,v){for(var k=0;k<b.length;k++)for(var r=b[k].w||[],J=0;J<r.length;J++)g(a,r[J],c,v)}function u(){L||(L=a.ue_cel.timeout(function(){L=
null;var a={x:d.pageXOffset,y:d.pageYOffset},c=q();e(v,c);for(var k=0;k<b.length;k++)g(J,b[k],c,a);m(c)},y))}function x(){L||K||(K=a.ue_cel.timeout(function(){K=null;var a={x:d.pageXOffset,y:d.pageYOffset},b=q();e(r,b,a);m(b)},y))}var y=50,c=4.5,q,b=[],G=function(){},E=a.ue_cel.log,f,A,C,z,M=d.MutationObserver||d.WebKitMutationObserver||d.MozMutationObserver,N=!!M,H,F,K,L,I=[],O=0,P=null,v="removedWidget",J="updateWidgets",r="processWidget",k,R=d.performance||{},U=R.now&&function(){return R.now()}||
function(){return Date.now()};"function"==typeof uet&&uet("bb","csmCELLSfem",{wb:1});return{on:function(c){function v(){if(C&&z&&f&&f.contains&&f.getBoundingClientRect&&q){k={removedWidget:t,updateWidgets:l,processWidget:h};if(N){var a={attributes:!0,subtree:!0};H=new M(x);F=new M(u);H.observe(f,a);F.observe(f,{childList:!0,subtree:!0});F.observe(A,a)}else C.call(f,"DOMAttrModified",x),C.call(f,"DOMNodeInserted",u),C.call(f,"DOMNodeRemoved",u),C.call(A,"DOMNodeInserted",x),C.call(A,"DOMNodeRemoved",
x);u()}}f=w.body;A=w.head;C=f.addEventListener;z=f.removeEventListener;q=c.ts;b=a.cel_widgets||[];P=c.bs||5;p.deffered?v():p.attach&&p.attach("load",v);"function"==typeof uex&&uex("ld","csmCELLSfem",{wb:1})},off:function(){C&&z&&f&&f.contains&&f.getBoundingClientRect&&q&&(F&&(F.disconnect(),F=null),H&&(H.disconnect(),H=null),z.call(f,"DOMAttrModified",x),z.call(f,"DOMNodeInserted",u),z.call(f,"DOMNodeRemoved",u),z.call(A,"DOMNodeInserted",x),z.call(A,"DOMNodeRemoved",x));p.count&&p.count("cel.widgets.batchesProcessed",
O)},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){b=a.cel_widgets||[]}}}():function(){function n(){a.ue_cel.timeout(function(){G.splice(0).forEach(function(a){E(a,{clog:1})})},0)}function h(a){for(var b={x:d.pageXOffset,y:d.pageYOffset},c=0;c<q.length;c++){var J=q[c];if(J.w&&J.w.length)for(var r=0;r<J.w.length;r++){var k=J.w[r],f;a:{try{var g=k,B=b;if(g){var e=g.getBoundingClientRect();f={x:e.left+B.x|0,y:e.top+B.y|0,w:e.width|0,h:e.height|0,d:(0===g.offsetWidth&&0===g.offsetHeight)|
0}}else f=void 0;break a}catch(Q){}f=void 0}if(f&&!k.cel_b)k.cel_b=f,G.push({n:k.cel_n,w:k.cel_b.w,h:k.cel_b.h,d:k.cel_b.d,x:k.cel_b.x,y:k.cel_b.y,t:a,k:"ewi",cl:k.className});else{if(g=f)g=k.cel_b,B=f,g=B.d===g.d&&1===B.d?!1:!(t(g.x,B.x)&&t(g.y,B.y)&&t(g.w,B.w)&&t(g.h,B.h)&&g.d===B.d);g&&(k.cel_b=f,G.push({n:k.cel_n,w:k.cel_b.w,h:k.cel_b.h,d:k.cel_b.d,x:k.cel_b.x,y:k.cel_b.y,t:a,k:"ewi"}))}}}}function l(a){for(var c=0;c<q.length;c++){var v=q[c],J;J=v;J=J.c?w.getElementsByClassName(J.c):J.id?[w.getElementById(J.id)]:
w.querySelectorAll(J.s);var r=v.w||[],k;for(k=0;k<r.length;k++){var d=r[k];f.contains(d)||G.push({n:d.cel_n,t:a,k:"ewd"})}v.w=[];for(k=0;k<J.length;k++)if(r=J[k])r.cel_n||(r.cel_n=r.getAttribute("cel_widget_id")||(v.id_gen||b)(r,k)||r.id),v.w.push(r)}g()}function t(a,b){return a>b?3>a-b:3>b-a}function m(){L||(L=a.ue_cel.timeout(function(){L=null;e("dwe",l);n()},u))}function g(){L||K||(K=a.ue_cel.timeout(function(){K=null;e("dwpc",h);n()},u))}function e(a,b){var v=c();b(v);var J=c(),v=J-v;v<=x?J=0:
J-I>=y?(I=J,J=0):(ue_fem.off(),J=1);(G.length||J)&&G.push({k:"ewt",e:a,d:v,ex:J,t:c()})}var u=50,x=10,y=3E3,c,q=[],b=function(){},G=[],E=a.ue_cel.log,f,A,C,z,M=d.MutationObserver||d.WebKitMutationObserver||d.MozMutationObserver,N=!!M,H,F,K,L,I=-y;"function"==typeof uet&&uet("bb","csmCELLSfem",{wb:1});return{on:function(b){function d(){if(C&&z&&f&&f.contains&&f.getBoundingClientRect&&c){if(N){var a={attributes:!0,subtree:!0};H=new M(g);F=new M(m);H.observe(f,a);F.observe(f,{childList:!0,subtree:!0});
F.observe(A,a)}else C.call(f,"DOMAttrModified",g),C.call(f,"DOMNodeInserted",m),C.call(f,"DOMNodeRemoved",m),C.call(A,"DOMNodeInserted",g),C.call(A,"DOMNodeRemoved",g);m()}}f=w.body;A=w.head;C=f.addEventListener;z=f.removeEventListener;c=b.ts;q=a.cel_widgets||[];p.deffered?d():p.attach&&p.attach("load",d);"function"==typeof uex&&uex("ld","csmCELLSfem",{wb:1})},off:function(){C&&z&&f&&f.contains&&f.getBoundingClientRect&&c&&(F&&(F.disconnect(),F=null),H&&(H.disconnect(),H=null),z.call(f,"DOMAttrModified",
g),z.call(f,"DOMNodeInserted",m),z.call(f,"DOMNodeRemoved",m),z.call(A,"DOMNodeInserted",g),z.call(A,"DOMNodeRemoved",g))},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){q=a.cel_widgets||[]}}}(),a.ue_cel&&a.ue_fem&&a.ue_cel.registerModule("features module",a.ue_fem))})(ue_csm,window,document);
(function(a,d){a.ue_mcm||a.ue.isBF||(a.ue_mcm=function(){function w(a){if(a.id)return"//*[@id='"+a.id+"']";var d;d=1;var u;for(u=a.previousSibling;u;u=u.previousSibling)u.nodeName==a.nodeName&&(d+=1);u=a.nodeName;1!=d&&(u+="["+d+"]");a.parentNode&&(u=w(a.parentNode)+"/"+u);return u}function p(a){var e=a.srcElement||a.target||{},u={k:n,w:d.body.scrollWidth,h:d.body.scrollHeight,t:h(),x:a.pageX,y:a.pageY,p:w(e),n:e.nodeName,e:m};a.button&&(u.b=a.button);e.href&&(u.r=e.href);e.id&&(u.i=e.id);e.className&&
(u.c=e.className.split(/\s+/));t(u,{c:1})}var n="mcm",h,l=a.ue,t=a.ue_cel.log,m=a.ue_mce||"click";return{on:function(a){h=a.ts;l.attach&&l.attach(m,p,d)},off:function(a){l.detach&&l.detach(m,p,d)},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){}}}(),a.ue_cel&&a.ue_cel.registerModule("mouse click module",a.ue_mcm))})(ue_csm,document);
(function(a,d){a.ue_mmm||a.ue.isBF||(a.ue_mmm=function(w){function p(a,b){var c={x:a.pageX||a.x||0,y:a.pageY||a.y||0,t:g()};!b&&M&&(c.t-M.t<l||c.x==M.x&&c.y==M.y)||(M=c,A.push(c))}function n(){if(A.length){E=K.now();for(var a=0;a<A.length;a++){var d=A[a],g=a;N=A[z];H=d;var e=void 0;if(!(e=2>g)){a:if(A[g].t-A[g-1].t>h)e=0;else{for(e=z+1;e<g;e++){var v=N,J=H,r=A[e];F=(J.x-v.x)*(v.y-r.y)-(v.x-r.x)*(J.y-v.y);if(F*F/((J.x-v.x)*(J.x-v.x)+(J.y-v.y)*(J.y-v.y))>t){e=0;break a}}e=1}e=!e}e?z=g-1:C.pop();C.push(d)}f=
K.now()-E;c=Math.min(c,f);q=Math.max(q,f);b=(b*G+f)/(G+1);G+=1;x({k:m,e:C,min:Math.floor(1E3*c),max:Math.floor(1E3*q),avg:Math.floor(1E3*b)},{c:1});A=[];C=[];z=0}}var h=100,l=20,t=25,m="mmm1",g,e,u=a.ue,x=a.ue_cel.log,y,c=1E3,q=0,b=0,G=0,E,f,A=[],C=[],z=0,M,N,H,F,K=w&&w.now&&w||Date.now&&Date||{now:function(){return(new Date).getTime()}};return{on:function(a){g=a.ts;e=a.ns;u.attach&&u.attach("mousemove",p,d);y=setInterval(n,3E3)},off:function(a){e&&(M&&p(M,!0),n());clearInterval(y);u.detach&&u.detach("mousemove",
p,d)},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){A=[];C=[];z=0;M=null}}}(window.performance),a.ue_cel&&a.ue_cel.registerModule("mouse move module",a.ue_mmm))})(ue_csm,document);